name: CICD Heroku Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  nodejs-backend-server-template:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Clonación de repositorio
      uses: actions/checkout@v2

    - name: Instalando NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 18.17.0

    - name: Instalando dependencias
      run: npm install
    - name: Construcción de Artefacto
      run: docker build -t backend .

    - name: Autenticación a Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push de Artefacto a Docker Hub
      run: |
        docker tag backend ${{ secrets.DOCKER_HUB_USERNAME }}/backend:stable
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:stable

    - name: Desplegar entorno de pruebas
      run: |
        docker-compose -f docker-compose.test.yml up -d
      env:
        DOCKER_IMAGE: backend:latest

    - name: Ejecución de pruebas en el dockerizado
      run: |
        docker exec $(docker ps -q -f "ancestor=${{ secrets.DOCKER_HUB_USERNAME }}/backend:stable") npm test
        echo "Aquí se ejecutan las pruebas de integración"
    
    - name: Detener entorno de pruebas
      run: |
        docker-compose -f docker-compose.test.yml down
    - name: Deploy a Producción
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "backendapp"
        heroku_email: ${{secrets.HEROKU_EMAIL}}



