name: CICD Heroku Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  nodejs-backend-server-template:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Clonación de repositorio
      uses: actions/checkout@v2

    - name: Instalando NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 18.17.0

    - name: Instalando dependencias
      run: npm install
    - name: Construcción de Artefacto
      run: docker build -t backend .

    - name: Autenticación a Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push de Artefacto a Docker Hub
      run: |
        docker tag backend ${{ secrets.DOCKER_HUB_USERNAME }}/backend:stable
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:stable


