name: CICD Kubernetes Pipeline

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  nodejs-backend-server-template:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Clonación de repositorio
      uses: actions/checkout@v2

    - name: Instalando NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 18.17.0

    - name: Instalando dependencias
      run: npm install

    - name: Corriendo pruebas unitarias
      uses: ArtiomTr/jest-coverage-report-action@v2
