name: CICD Kubernetes Pipeline

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  nodejs-backend-server-template:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Clonación de repositorio
      uses: actions/checkout@v2

    - name: Instalando NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 18.17.0

    - name: Instalando dependencias
      run: npm install

    - name: Corriendo pruebas unitarias
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        github-token: ${{ secrets.SECRET_TOKEN }}
        annotations: none

    - name: Análisis de Código Estático con ESLint
      uses: sibiraj-s/action-eslint@v3
      with:
        eslint-args: '--ignore-path=.gitignore --quiet'
        extensions: 'js,jsx,ts,tsx'
        annotations: true

    - name: Construcción de Artefacto
      run: docker build -t backend .

    - name: Trivy Security
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: 'backend'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Autenticación a Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push de Artefacto a Docker Hub
      run: |
        docker tag backend ${{ secrets.DOCKER_HUB_USERNAME }}/backend:stable
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:stable

    - name: Desplegar entorno de pruebas
      run: |
        docker-compose -f docker-compose.test.yml up -d
      env:
        DOCKER_IMAGE: backend:latest

    - name: Ejecución de pruebas en el dockerizado
      run: |
        docker exec $(docker ps -q -f "ancestor=${{ secrets.DOCKER_HUB_USERNAME }}/backend:stable") npm test
        echo "Aquí se ejecutan las pruebas de integración"
    
    - name: Detener entorno de pruebas
      run: |
        docker-compose -f docker-compose.test.yml down

    - name: Autenticación a Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login ${HEROKU_API_KEY}" >> ~/.netrc
        echo "machine git.heroku.com" >> ~/.netrc
        echo "  login ${HEROKU_API_KEY}" >> ~/.netrc

    - name: Push a Heroku
      run: |
        docker tag backend registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      
    - name: Release en Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        curl -n -X PATCH https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }}/formation \
        -d '{"updates":[{"type":"web","docker_image":"registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web"}]}' \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
        -H "Authorization: Bearer $HEROKU_API_KEY"



