name: CICD Kubernetes Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clone-install-deps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.17.1

    - name: Install dependencies
      run: npm install